# Generated by Django 5.1.2 on 2024-10-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
